USE world;

CREATE TABLE country (
  Code VARCHAR(3) PRIMARY KEY,
  Name VARCHAR(255) NOT NULL DEFAULT "",
  Continent VARCHAR(50) NOT NULL DEFAULT "",
  Region VARCHAR(50) NOT NULL DEFAULT "",
  SurfaceArea FLOAT NOT NULL DEFAULT 0.00,
  IndepYear INT DEFAULT NULL,
  Population INT NOT NULL DEFAULT 0,
  LifeExpectancy FLOAT DEFAULT NULL,
  GNP FLOAT DEFAULT NULL,
  GNPOld FLOAT DEFAULT NULL,
  LocalName VARCHAR(50) NOT NULL DEFAULT "",
  GovernmentForm VARCHAR(50) NOT NULL DEFAULT "",
  HeadOfState VARCHAR(80) DEFAULT NULL,
  Capital INT DEFAULT NULL,
  Code2 VARCHAR(3) NOT NULL DEFAULT ""
);

CREATE TABLE city (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  Name VARCHAR(255) NOT NULL DEFAULT "",
  CountryCode VARCHAR(3) NOT NULL DEFAULT "",
  District VARCHAR(255) NOT NULL DEFAULT "",
  Population INT NOT NULL DEFAULT 0,
  FOREIGN KEY (CountryCode) REFERENCES country (Code)
);

CREATE TABLE `countrylanguage` (
  CountryCode VARCHAR(3),
  Language VARCHAR(50),
  IsOfficial ENUM('T','F') NOT NULL DEFAULT 'F',
  Percentage FLOAT NOT NULL DEFAULT 0.00,
  PRIMARY KEY (CountryCode, Language),
  FOREIGN KEY (CountryCode) REFERENCES country (Code)
);

